using System.Collections.Generic;
using System.Reflection.Emit;
using HarmonyLib;

namespace AstrylsUIZhCN
{
    /// <summary>
    /// Hardcoded string translation core (2026-08-02: direct literal replacement).
    ///
    /// Design:
    /// - Chinese text is embedded directly in this DLL; no Translator call, no language file loading.
    /// - Transpiler replaces the original mod ldstr English with ldstr Chinese directly.
    /// - Changing translations requires recompiling the DLL (trading hot-update for reliability).
    /// </summary>
    public static class HardcodedStringReplacer
    {
        /// <summary>Original English hardcoded string -> Chinese literal.</summary>
        public static readonly Dictionary<string, string> KeyForString = new Dictionary<string, string>
        {
            // 组织结构说明：
            // - 拼接片段（带空格 / 标点 / 换行前缀的 key）集中在前部，便于统一检索
            // - 完整词条大致按字母序排列
            // - 各模组专属条目用 // ===== 区块注释分隔
            // 新增条目：先查重（禁止重复英文 key，否则静态构造崩溃导致全部补丁失效）
            { " - combat readiness ", " - 战斗准备度 " },
            { " - press ", " - 按 " },
            { " (", "（" },
            { " (armor ", "（护甲 " },
            { " (click to cycle)", "（点击循环）" },
            { " (empty) - left-click to filter add-list, right-click to clear", "（空）- 左键点击过滤添加列表，右键点击清除" },
            { " (from selection)", "（从选中）" },
            { " (health, consciousness, mobility)", "（健康、意识、移动力）" },
            { " (in hand)", "（手持）" },
            { " (sidearm)", "（副武器）" },
            { " + add", " + 添加" },
            { " apparel item", "件服装物品" },
            { " blunt, vs ", "钝击，对比 " },
            { " c/s", "格/秒" },
            { " crafting bill(s) for ", "个制作清单用于" },
            { " DPS)", " DPS）" },
            { " effective DPS, ", "有效 DPS，" },
            { " expected)", "预期）" },
            { " faction", "个派系" },
            { " factions", "个派系" },
            { " for ", "用于" },
            { " has nothing to tend.", "没有可治疗的对象。" },
            { " hostile", "敌对" },
            { " is incapable of violence.", "无法使用暴力。" },
            { " more", "更多" },
            { " on the bar", "在条上" },
            { " pawn", "名小人" },
            { " policy: ", "政策：" },
            { " prisoner", "囚犯" },
            { " ready", "就绪" },
            { " selected", " 名已选中" },
            { " selected here", "名已选在此" },
            { " selected pawns", "名已选小人" },
            { " selected\n", "已选中\n" },
            { " sharp / ", "锐利 / " },
            { " slave", "奴隶" },
            { " the nearest available one", "最近的可用的那个" },
            { " this", "这个" },
            { " to ", "到" },
            { " unavailable", "不可用" },
            { " x", "个" },
            { "% hit)", "% 命中）" },
            { "(none)", "（无）" },
            { ") for ", "）用于" },
            { "):", "）：" },
            { ", avg combat power ", "，平均战斗力量 " },
            { ", vs ", "，对比 " },
            { ": none carried", "：未携带" },
            { "\" set from kit (", "\" 从套装设置（" },
            { "\n(click to change)", "\n（点击更改）" },
            { "\n\n(click to filter the add-list below)", "\n\n（点击过滤下方的添加列表）" },
            { "\n\nAdjusted DPS (", "\n\n调整后 DPS（" },
            { "\n\nClick to jump there.", "\n\n点击跳转" },
            { "\n\nCondition ", "\n\n状态 " },
            { "\n\nWorld benchmark: ", "\n\n世界基准：" },
            { "\nApplies to ", "\n适用于" },
            { "\nBleeding: ", "\n出血：" },
            { "\nBlood: ", "\n血液：" },
            { "\nClick: use one", "\n点击：使用一个" },
            { "\nDefense ", "\n防御 " },
            { "\nIncapable of violence: x0.15", "\n无法使用暴力：x0.15" },
            { "\nOffense ", "\n进攻 " },
            { "\nOptimal range: ", "\n最佳射程：" },
            { "\nRange: ", "\n射程：" },
            { "\nSustained DPS: ", "\n持续 DPS：" },
            { "+ New squad", "+ 新建小队" },
            { "✓ available x", "✓ 可用 x" },
            { "A colony-wide skills & passions summary.\n\nPassion breakdown across all colonists, skill milestone counts (maxed / expert / skilled), and how many colonists are actively learning right now. Derived entirely from your colonists' skills — not the vanilla tutorial Learning Helper.", "全殖民地的技能与热情摘要。\n\n所有殖民者的热情分布、技能里程碑数量（满级 / 专家 / 熟练），以及当前有多少殖民者在积极学习。完全源自你殖民者的技能——不是原版教程的学习助手。" },
            // ===== Learning Menu 技能面板统计 + VSE 模组缺失提示 =====
            { "\nActive — data shown in the dashboard.", "\n已激活 — 数据已显示在面板中。" },
            { "\nNot loaded — install/enable to see its data here.", "\n未加载 — 安装/启用它以在此处查看数据。" },
            { "SKILL MILESTONES", "技能里程碑" },
            { "How skilled your colony is overall. Counts every enabled skill across all colonists.", "整个殖民地的技能水平概览。统计所有殖民者所有已启用的技能。" },
            { "Expert (15-19)", "专家 (15-19)" },
            { "Skilled (10-14)", "熟练 (10-14)" },
            { "Average skill level", "平均技能等级" },
            { "LEARNING NOW", "正在学习" },
            { "Colonists actively learning right now - children with the Learning need, growth-vat occupants, and anyone at a learning desk or training station.", "当前正在学习的殖民者——有学习需求的儿童、生长缸占用者，以及任何在学习桌或训练站的人。" },
            { "Children learning", "正在学习的儿童" },
            { "In growth vats", "生长缸内" },
            { "BIOTECH — VAT LEARNING", "生物科技 — 生长缸学习" },
            { " has no expertise records yet.", " 还没有专精记录。" },
            { "Ability", "能力" },
            { "Active skill-training in progress.\n\nGrowth-vat learning (Biotech / Enhanced Vat Learning): vat occupants and their progress toward the next skill XP award.\nSimple Learning: who is at a learning desk and what they're studying.\nMisc. Training: who is using training equipment and the skill they're practising.", "进行中的活跃技能训练。\n\n生长缸学习（生物科技 / 增强缸学习）：缸中占用者及其朝向下一次技能经验奖励的进度。\nSimple Learning：谁在学习桌前以及他们在学什么。\nMisc. Training：谁在使用训练设备以及他们练习的技能。" },
            { "Active Training", "活跃训练" },
            { "Add stat", "添加统计" },
            { "All", "全部" },
            { "All milestones passed", "所有里程碑已通过" },
            { "all slots", "所有栏位" },
            { "Apply to ", "应用于" },
            { "Armor - blunt", "护甲 - 钝击" },
            { "Armor - heat", "护甲 - 高温" },
            { "Armor - sharp", "护甲 - 锐利" },
            { "Assign ", "分配" },
            { "Assign ideoligion role", "分配意识形态角色" },
            { "Assign selection to squad", "将选中分配至小队" },
            { "Auto-hide corpses", "自动隐藏尸体" },
            { "Auto-hide mechs / mutants", "自动隐藏机械体 / 变异体" },
            { "Auto-hide slaves", "自动隐藏奴隶" },
            { "Awards 8000 XP to a random skill when full.\nVat: ", "满时向随机技能奖励 8000 经验。\n缸：" },
            { "Bar controls - views, hidden pawns, squads, settings\nRight-click: open the Command center", "条控制 - 视图、隐藏的小人、小队、设置\n右键：打开指挥中心" },
            { "Bar mode: ", "条模式：" },
            { "Bar squads", "条小队" },
            { "Bar view: ", "条视图：" },
            { "Beer", "啤酒" },
            { "Bio", "生物" },
            { "Blood pressure: ", "血压：" },
            { "Break up with ", "与…分手 " },
            { "Break: ", "崩溃：" },
            { "buy / quest only", "仅购买 / 任务" },
            { "cannot reach", "无法到达" },
            { "cannot wear", "无法穿戴" },
            { "Carry as sidearm - ", "作为副武器携带 - " },
            { "Catalog", "目录" },
            { "Child Development", "儿童发展" },
            { "Child development tracking (requires Biotech).\n\nOne card per child colonist: growth tier (0–8) shown as diamonds, growth-point progress to the next tier, the Learning need bar, active learning desires, and — with Children School & Learning — their school schedule. A ⚡ badge appears when a growth moment is ready.", "儿童发展追踪（需要生物科技）。\n\n每个儿童殖民者一张卡片：成长等级（0–8）以菱形显示、到下一等级的成长点数进度、学习需求条、活跃的学习渴望，以及——配合儿童学校与学习——他们的学校时间表。成长时刻就绪时会显示 ⚡ 徽章。" },
            { "Choose which social stats to display", "选择要显示的社交统计" },
            { "Click to change color", "点击更改颜色" },
            { "Click to change icon", "点击更改图标" },
            { "Click to remove from the graph", "点击从图表中移除" },
            { "Colony Skills", "殖民地技能" },
            { "Columns...", "列..." },
            { "Combat readiness", "战斗准备度" },
            { "Command center...", "指挥中心..." },
            { "Cond", "状态" },
            { "Configure card bars", "配置卡片条" },
            { "Consciousness", "意识" },
            { "Current contributors", "当前贡献者" },
            { "Cycle icon", "循环图标" },
            { "Danger sense: ", "危险感知：" },
            { "dead", "已死亡" },
            { "deceased", "已故" },
            { "Default filter", "默认过滤" },
            { "Default sort", "默认排序" },
            { "Defend", "防御" },
            { "Delete ", "删除" },
            { "different map", "不同地图" },
            { "Disband squad", "解散小队" },
            { "Draft", "征召" },
            { "Drafted", "已征召" },
            { "Drug", "药物" },
            { "Drugs", "药物" },
            { "Drugs: ", "药物：" },
            { "Edit current policy...", "编辑当前政策..." },
            { "elsewhere in the world", "在世界的其他地方" },
            { "Elsewhere.", "他处" },
            { "Emergency", "紧急状态" },
            { "Empty kit - click the paperdoll slots to add gear.", "空套装 - 点击纸娃娃栏位添加装备。" },
            { "End emergency", "结束紧急状态" },
            { "End emergency (Better Pawn Control)", "结束紧急状态（Better Pawn Control）" },
            { "Engagement: ", "交战：" },
            { "equip", "装备" },
            { "Equip on ", "装备到" },
            { "-era enemies", "时代敌人" },
            { "Every colonist's skill levels at a glance.\n\nColumns are colonists, rows are the 12 skills. Each cell shows the level, an XP progress bar, and a passion icon (fire = vanilla, custom icons from Vanilla Skills Expanded). Hover any cell for XP detail. Scrolls horizontally for large colonies.", "一眼概览每位殖民者的技能等级。\n\n列是殖民者，行是 12 项技能。每个单元格显示等级、经验进度条和热情图标（火焰 = 原版，自定义图标来自原版技能扩展）。悬停任一单元格可查看经验详情。大型殖民地可水平滚动。" },
            { "Everyone", "所有人" },
            { "EVL Enhanced", "EVL 增强" },
            { "Factors", "因素" },
            { "fists", "拳头" },
            { "focus: ", "焦点：" },
            { "Follow with camera", "镜头跟随" },
            { "Following ", "跟随" },
            { "Food", "食物" },
            { "Food: ", "食物：" },
            { "forbidden", "被禁止" },
            { "Formal education systems.\n\nRim Education: each colonist's education level + progress to the next.\nProgression: Education: scheduled classes with teacher, students, and progress.\nChildren School & Learning: each child's school hours and current status.", "正式教育系统。\n\nRim Education：每位殖民者的教育等级 + 到下一级的进度。\nProgression：Education：已排课的班级，含教师、学生和进度。\n儿童学校与学习：每个孩子的上课时间和当前状态。" },
            { "Forming caravan", "组建商队" },
            { "Gear", "装备" },
            { "Gear up - availability + materials", "装备 - 可用性 + 材料" },
            { "group readiness", "队伍就绪度" },
            { "Group readiness - average of ", "队伍就绪度 - 平均值" },
            { "Growth Moments", "成长时刻" },
            { "Growth points: {0:F1} / {1:F0}", "成长点数：{0:F1} / {1:F0}" },
            { "Health", "健康" },
            { "Heat", "热度" },
            { "Hide from bar", "从条上隐藏" },
            { "Hide kit preview on the paperdoll", "在纸娃娃上隐藏套装预览" },
            { "Hide the prisoner section from the bar", "从条上隐藏囚犯区域" },
            { "Hide the slave section from the bar", "从条上隐藏奴隶区域" },
            { "History", "历史" },
            { "How {0} currently feels about {1}: {2}{3}.", "{0} 目前对 {1} 的感觉：{2}{3}。" },
            { "How many days of standing history to keep. Shorter windows use less memory and save space.", "保留多少天的关系历史。更短的窗口使用更少内存并节省空间。" },
            { "How often social standing is sampled. Longer intervals cost less performance in large colonies.", "关系状态采样的频率。在大型殖民地中，更长的间隔开销更低。" },
            { "How often the relationship list refreshes while the tab is open, in frames. Higher is lighter on frame rate; lower updates opinions and relationships more responsively.", "标签页打开期间关系列表刷新的频率（以帧计）。更高对帧率更友好；更低更新好感度和关系更灵敏。" },
            { "How relation cards are ordered. Pinned pawns always stay on top; off-map pawns sink to the bottom.", "关系卡片的排序方式。固定的小人始终保持在顶部；地图外的小人会沉到底部。" },
            { "How this is calculated", "这是如何计算的" },
            { "How well-liked ", "受欢迎程度" },
            { "Ideoligion certainty: ", "意识形态信仰坚定度：" },
            { "idle", "空闲" },
            { "In transit.", "运输中" },
            { "incapable", "无法" },
            { "incapable of violence", "无法使用暴力" },
            { "Industrial", "工业" },
            { "Inspired: ", "灵感：" },
            { "item unavailable", "物品不可用" },
            { "Jump", "跳转" },
            { "Jump to", "跳转到" },
            { "Jump to ", "跳转到" },
            { "Jump to item", "跳转到物品" },
            { "Jump to weapon", "跳转到武器" },
            { "Kit ", "套装" },
            { "Kits", "套装" },
            { "Layout locked — left-click to unlock (enables drag / resize / minimise)", "布局已锁定——左键点击解锁（启用拖动 / 调整大小 / 最小化）" },
            { "Layout unlocked — left-click to lock (prevents accidental changes)", "布局已解锁——左键点击锁定（防止意外更改）" },
            { "Leader", "领袖" },
            { "Learning Summary", "学习摘要" },
            { "Leave ", "离开" },
            { "Leave squad", "离开小队" },
            { "Lock layout", "锁定布局" },
            { "long", "长" },
            { "Major passions", "重度热情" },
            { "Manage on bar (squads / views / hide)", "在条上管理（小队 / 视图 / 隐藏）" },
            { "Manage squads (reorder / rename / recolor)...", "管理小队（重排 / 重命名 / 重新着色）..." },
            { "Manage squads...", "管理小队..." },
            { "Manipulation", "操作" },
            { "material", "材料" },
            { "Medical rest", "医疗休养" },
            { "medium", "中" },
            { "Melee", "近战" },
            { "Melee DPS", "近战 DPS" },
            { "Melee hit", "近战命中" },
            { "Mental health", "心理健康" },
            { "Mental health (MMB)", "心理健康（MMB）" },
            { "Mind", "心灵" },
            { "Minor passions", "轻度热情" },
            { "Modern Colonist Bar", "现代殖民者栏" },
            { "Modern Colonist Bar settings", "现代殖民者栏设置" },
            { "Modern Colonist Bar settings...", "现代殖民者栏设置..." },
            { "Module error: ", "模块错误：" },
            { "Mood", "心情" },
            { "Mood: ", "心情：" },
            { "Move down", "下移" },
            { "Move speed", "移动速度" },
            { "Move to ", "移动到" },
            { "Move up", "上移" },
            { "Moving", "移动" },
            { "Needs tending", "需要治疗" },
            { "Needs treatment", "需要治疗" },
            { "Neural heat", "神经热度" },
            { "New empty kit", "新建空套装" },
            { "New from ", "新建自" },
            { "New squad", "新建小队" },
            { "New squad (move here)", "新建小队（移到这里）" },
            { "New squad...", "新建小队..." },
            { "New view from selection (", "从选中新建视图（" },
            { "Next milestone at age {0} ({1} years away)", "下一个里程碑在 {0} 岁（还有 {1} 年）" },
            { "Next: +{0} trait choices", "下一个：+{0} 个特性选择" },
            { "No available pawn for that order.", "该命令没有可用的小人。" },
            { "No body observations yet.", "尚无身体观察。" },
            { "No child colonists — no growth moments to track.", "没有儿童殖民者——没有成长时刻可追踪。" },
            { "No child colonists on map.", "地图上没有儿童殖民者。" },
            { "No classes set up. Use the Progression: Education tab to create classes.", "未设置课程。使用 Progression：Education 标签页创建课程。" },
            { "No colonists currently in growth vats.", "当前没有殖民者在生长缸中。" },
            { "No colonists on map.", "地图上没有殖民者。" },
            { "No colonists training right now.", "当前没有殖民者在训练。" },
            { "No colonists.", "没有殖民者。" },
            { "No craftable items or capable benches found for ", "未找到可制作物品或可用工作台用于" },
            { "No education mods detected.\nLoad Progression: Education, Rim Education, or CSL.", "未检测到教育模组。\n加载 Progression：Education、Rim Education 或 CSL。" },
            { "No kit selected", "未选择套装" },
            { "No known relationships.", "没有已知关系。" },
            { "No map to add bills to.", "没有地图可添加制作清单。" },
            { "No matching gear on the map.", "地图上没有匹配的装备。" },
            { "no pawn selected", "未选择小人" },
            { "No pawn selected.", "未选择小人。" },
            { "No pawns match.", "没有匹配的小人。" },
            { "No policies available", "没有可用政策" },
            { "No reachable ", "没有可到达的" },
            { "No recent interactions.", "没有近期互动。" },
            { "No school scheduled", "未安排课程" },
            { "No squads yet. Create one, then assign pawns via right-click > Manage on bar.", "还没有小队。创建一个，然后通过右键 > 在条上管理 来分配小人。" },
            { "No teacher", "无教师" },
            { "No training mods detected.\nLoad Biotech, Simple Learning, or Misc. Training.", "未检测到训练模组。\n加载生物科技、Simple Learning 或 Misc. Training。" },
            { "No weapons found.", "未找到武器。" },
            { "Not possible", "不可能" },
            { "Not scheduled", "未安排" },
            { "Nothing in particular.", "没什么特别的。" },
            { "On another map.\n\nClick to jump there.", "在另一张地图。\n\n点击跳转" },
            { "On another map: ", "在另一张地图：" },
            { "On map", "地图上" },
            { "on the current map", "在当前地图上" },
            { "Opinion", "好感度" },
            { "Order ", "命令" },
            { "Outfit", "服装" },
            { "Outfit policy \"", "服装政策 \"" },
            { "Outfit: ", "服装：" },
            { "Pain", "疼痛" },
            { "Party cards", "派对卡片" },
            { "pawn", "小人" },
            { "Pawn stats", "小人统计" },
            { "Permanently disabled for this pawn.", "对此小人永久禁用。" },
            { "Pin to the top of the list", "固定到列表顶部" },
            { "Policies (outfit / food / drugs)", "政策（服装 / 食物 / 药物）" },
            { "Prevent dragging, resizing, and minimising panels.", "防止拖动、调整大小和最小化面板。" },
            { "Preview this kit on the paperdoll", "在纸娃娃上预览此套装" },
            { "prisoner", "囚犯" },
            { "Progression Dashboard layout reset to defaults.", "进度仪表盘布局已重置为默认值。" },
            { "Propose marriage to ", "向…求婚 " },
            { "Psy", "心灵" },
            { "Psyfocus", "心灵聚焦" },
            { "Quality", "品质" },
            { "Queue bills", "排队制作清单" },
            { "Queued ", "已排队" },
            { "Range", "射程" },
            { "Ranged", "远程" },
            { "Ranged DPS", "远程 DPS" },
            { "readiness", "就绪度" },
            { "Ready", "就绪" },
            { "Recent interactions", "近期互动" },
            { "Record standing history", "记录关系历史" },
            { "Recording opinion…\nthe graph fills in over time.", "正在记录好感…\n图表会随时间填充。" },
            { "Records each colonist's social standing every few in-game hours so the graph can show history. Turn this off to remove all per-tick work from this mod; the graph then shows only the live value.", "每隔几个游戏小时记录每位殖民者的关系状态，以便图表显示历史。关闭可移除本模组所有每 tick 工作；图表随后只显示实时值。" },
            { "Relation", "关系" },
            { "Relation list", "关系列表" },
            { "Relations", "关系" },
            { "Remove ", "移除" },
            { "Rename", "重命名" },
            { "Rename ", "重命名" },
            { "Rename / recolor...", "重命名 / 重新着色..." },
            { "Rename or recolor", "重命名或重新着色" },
            { "Requires Biotech DLC.", "需要生物科技 DLC。" },
            { "Requires Vanilla Skills Expanded.", "需要原版技能扩展。" },
            { "Reset layout to defaults", "将布局重置为默认值" },
            { "Reset to defaults", "重置为默认" },
            { "Restore window scale, sort/filter, and the displayed social stats to defaults.", "将窗口缩放、排序/过滤以及显示的社交统计恢复为默认值。" },
            { "Riding a mount", "骑乘坐骑" },
            { "Right-click: open as a submenu without closing this menu.", "右键：作为子菜单打开而不关闭此菜单。" },
            { "Search...", "搜索..." },
            { "Select ", "选择" },
            { "Select a kit to edit + see requirements.", "选择要编辑的套装并查看需求。" },
            { "Select a pawn to follow.", "选择要跟随的小人。" },
            { "Select a pawn.", "选择一个小人。" },
            { "Select or create a kit on the right to edit one.", "在右侧选择或创建套装进行编辑。" },
            { "Selected", "已选中" },
            { "Set allowed outfit from kit", "从套装设置允许的服装" },
            { "Sets the Social tab's width (60% to 100% of its base width); the height is always full. The tab also auto-fits to your resolution and UI scale, so it never runs off-screen.", "设置社交标签页的宽度（为其基础宽度的 60% 到 100%）；高度始终为满。标签页也会自动适应你的分辨率和 UI 缩放，因此永远不会超出屏幕。" },
            { "Shoot accuracy", "射击精度" },
            { "Shooting", "射击" },
            { "short", "短" },
            { "Show ", "显示" },
            { "Show: all", "显示：全部" },
            { "Show: colonists", "显示：殖民者" },
            { "Show: prisoners", "显示：囚犯" },
            { "Show: slaves", "显示：奴隶" },
            { "Shrinks the whole dashboard uniformly. 100% = auto-fit to screen.", "整体缩小整个仪表盘。100% = 自动适应屏幕。" },
            { "Sidearms", "副武器" },
            { "Sight", "视力" },
            { "slave", "奴隶" },
            { "Social", "社交" },
            { "Social stats", "社交统计" },
            { "Sort by health", "按健康排序" },
            { "Sort by mood", "按心情排序" },
            { "Sort by name", "按名字排序" },
            { "Sort by squad", "按小队排序" },
            { "Squad", "小队" },
            { "Squad: ", "小队：" },
            { "Standing", "关系状态" },
            { "Start emergency (Better Pawn Control)", "开始紧急状态（Better Pawn Control）" },
            { "Stop following", "停止跟随" },
            { "Stopped following.", "已停止跟随。" },
            { "storage", "仓库" },
            { "Switch to Modern Social Tab", "切换到现代社交标签页" },
            { "Switch to vanilla Social tab", "切换到原版社交标签页" },
            { "Targeted by ", "被攻击：" },
            { "Tend (medicine)", "治疗（药物）" },
            { "the follow key", "跟随键" },
            { "Their opinion of you", "他们对你的好感" },
            { "Thoughts on ", "关于…的想法 " },
            { "Top bar", "顶部条" },
            { "touch", "触摸" },
            { "travelling in a caravan", "在商队中旅行" },
            { "travelling in a caravan (", "在商队中旅行（" },
            { "Unarmed", "徒手" },
            { "Unassigned", "未分配" },
            { "unavailable", "不可用" },
            { "Unavailable outside a game", "游戏外不可用" },
            { "Undraft", "取消征召" },
            { "Unhide all", "全部取消隐藏" },
            { "Unhide all (", "全部取消隐藏 (" },
            { "Unhide pawns (", "取消隐藏小人（" },
            { "unknown", "未知" },
            { "Unknown pawn", "未知小人" },
            { "Unpin (return to normal sort order)", "取消固定（恢复正常排序顺序）" },
            { "Value", "价值" },
            { "Vanilla Skills Expanded — Expertise (requires VSE).\n\nExpertise is a separate progression system from the 12 normal skills: specialized knowledge tracks, each with its own level (0–20) and XP. Pick a colonist from the pill row to see their expertise records.", "原版技能扩展——专精（需要 VSE）。\n\n专精是与 12 项普通技能分开的独立进度系统：专业化的知识轨道，每条轨道有自己的等级（0–20）和经验。从药丸行选择一位殖民者以查看其专精记录。" },
            { "View: ", "查看：" },
            { "Violence", "暴力" },
            { "VSE Expertise", "VSE 专精" },
            { "VSE passions", "VSE 热情" },
            { "Weapon", "武器" },
            { "wear", "穿戴" },
            { "Wear on ", "穿戴到" },
            { "Where", "位置" },
            { "Which relationships to show: everyone, blood family, lovers (lover/fiancé/spouse), or rivals (negative opinion either way).", "要显示哪些关系：所有人、血亲、恋人（恋人/未婚夫/未婚妻/配偶）或对手（任一方有负面好感）。" },
            { "With caravan: ", "随商队：" },
            { "Your opinion of them", "你对他们的好感" },
            // ===== Circinus 主窗口 CircinusView（硬编码界面） =====
            { ". Click to cancel and put the game speed back.", "。点击取消并恢复游戏速度。" },
            { " error classes", " 个错误类别" },
            { "Baseline: ", "基线：" },
            { "Begin recording performance, errors and test results.", "开始记录性能、错误和测试结果。" },
            { "Close", "关闭" },
            { "Cohorts", "队列" },
            { "Drive the game through normal, fast, superfast and ultrafast, ", "依次以普通、快速、超快和极速驱动游戏，" },
            { "End this run and write it to disk.", "结束本次运行并写入磁盘。" },
            { "Errors", "错误" },
            { "Findings", "发现" },
            { "Live", "实时" },
            { "Live run, updating while recording.", "实时运行，记录期间持续更新。" },
            { "Load a game before recording a run.", "请先加载游戏再记录运行。" },
            { "Mods", "模组" },
            { "No baseline pinned", "未固定基线" },
            { "No run selected. Pick one on the Runs tab, or start recording.", "未选择运行。请在「运行」标签页选择，或开始记录。" },
            { "none", "无" },
            { "Not recording", "未在记录" },
            { "Patches", "补丁" },
            { "Perf", "性能" },
            { "Profiler", "分析器" },
            { "Recording ", "正在记录 " },
            { "Run ", "运行 " },
            { "Running ", "正在运行 " },
            { "Runs", "运行" },
            { "s in total, so this run has comparable samples at every speed.\n\nTick rate is capped by the game speed, so two runs can only be compared within one speed, and only at speeds they both recorded.", "秒总计，因此本次运行在每个速度下都有可比的样本。\n\n帧率受游戏速度限制，因此两次运行只能在同一速度内比较，且仅在两者都记录的速度下比较。" },
            { "s, ", "秒， " },
            { "Speed sweep", "速度扫描" },
            { "Start a run first. A sweep outside a recording changes the game speed and measures nothing.", "请先开始运行。录制之外的扫描会改变游戏速度但不会测量任何内容。" },
            { "Start run", "开始运行" },
            { "Stop and save", "停止并保存" },
            { "Stress", "压力" },
            { "Sweep ", "扫描 " },
            { "Tests", "测试" },
            { "Viewing run ", "正在查看运行 " },
            // ===== Circinus 补充（RunRecorder / Tab_Runs / Tab_Perf / Warmup） =====
            { "Automatic: instrumenting ", "自动插桩：" },
            { " patch method(s) progressively.", " 个补丁方法（渐进式）。" },
            { "Instrumenting Harmony patches. These first seconds are recorded but excluded from the run's results, so startup cost is not counted as a regression.", "正在插桩 Harmony 补丁。这些最初的几秒会被记录但排除在运行结果之外，因此启动开销不会被计入回归。" },
            { "Label", "名称" },
            { "Started", "开始时间" },
            { "Samples", "样本" },
            { "Machine", "机器" },
            { "not recorded (run predates schema 1.7)", "未记录（运行早于 schema 1.7）" },
            { "Calibration index", "校准指数" },
            { " (list ", "（列表 " },
            { "Harmony patches", "Harmony 补丁" },
            { "Instrumenting cost", "插桩开销" },
            { "Profiling", "分析" },
            { "active, forced by this mod", "活动，由本模组强制" },
            { "active, armed by hand", "活动，手动武装" },
            { "not active, no profiling data", "未活动，无分析数据" },
            { "Recorded under schema ", "记录于 schema " },
            { "Adapters", "适配器" },
            { "Pin as baseline", "固定为基线" },
            { "Use this run as the comparison baseline. Chosen explicitly so it never changes underneath you.", "将本次运行用作比较基线。显式选择，因此绝不会在你之下悄悄变化。" },
            { "Clear baseline", "清除基线" },
            { "Delete run", "删除运行" },
            { "Permanently delete this run file.", "永久删除此运行文件。" },
            { "Delete run ", "删除运行 " },
            { " permanently? This cannot be undone.", " ？此操作无法撤销。" },
            { "\n\nThis is recorded as no data, not as zero cost, so it cannot be mistaken for an improvement.", "\n\n这被记录为「无数据」而非「零开销」，因此不会被误认为性能提升。" },
            // ===== Modern Faction Menu（世界地图查看 tooltip） =====
            { "\n\nClick to view on the world map.", "\n\n点击查看世界地图" },
            { "View on the world map", "查看世界地图" },
            { "\n\nView on the world map.", "\n\n查看世界地图" },
            { "Collecting data... graphs appear after a few in-game hours (", "正在收集数据…几个游戏小时后图表才会出现（" },
            { "/2 samples).", "/2 个样本）。" },
            // ===== Modern Faction Menu 好感详情（Natural goodwill / Goodwill breakdown） =====
            { "Natural goodwill", "自然好感" },
            { "Goodwill ", "好感 " },
            { "  (natural pull ", "  （自然影响 " },
            { ")", "）" },
            // ===== Circinus 缺失提示 / 热点 / 成本面板补充 =====
            { "Needs attention", "需要注意" },
            { "Needs attention (", "需要注意（" },
            { "Nothing flagged.\n\nArm a profiler target to surface expensive mods and patches here.", "没有标记项。\n\n启用一个分析器目标，以在此处显示高开销的模组和补丁。" },
            { "Nothing flagged. No instrumented method is costing significant frame time and no errors have been captured.", "没有标记项。没有插桩方法占用显著帧时间，也未捕获到错误。" },
            { "not measured", "未测量" },
            { "no cost recorded", "未记录成本" },
            { "Measured here", "此处测量" },
            { "Share of frame", "帧占比" },
            { "Cost in window", "窗口内成本" },
            { "Patches profiled", "已分析补丁" },
            { "Error classes", "错误类别" },
            { "Across the corpus", "语料库对比" },
            { "corpus: not measured\n", "语料库：未测量\n" },
            { "not measured on this machine", "未在本机测量" },
            { "Profiler not armed for this run, so no cost data was recorded.", "本次运行未启用分析器，因此未记录成本数据。" },
            { "The profiler was not armed for this run, so no cost data was recorded.\n\nArm a target on the Profiler tab before recording.", "本次运行未启用分析器，因此未记录成本数据。\n\n录制前先在「性能分析器」标签页启用一个目标。" },
            { "Profiling was not active for this run.\n\nThis run was recorded under schema ", "本次运行未进行性能分析。\n\n本次运行在架构 " },
            { ", before profiling diagnostics were added, so no reason was captured. Record a new run to get an explanation.", " 下记录，早于性能分析诊断功能加入，因此未捕获原因。录制一次新运行以获取说明。" },
            { "Profiling was not active for this run, so no cost data was recorded.", "本次运行未进行性能分析，因此未记录成本数据。" },
            { "Mods by measured patch cost (", "按已测量补丁成本排序的模组（" },
            { "No per-mod cost recorded for this run.", "本次运行未记录每个模组的成本。" },
        };

        /// <summary>
        /// Modern CC 体型按钮文本：BodyTypeDef.defName → 中文（原版 5 种体型）。
        /// 未知 defName（第三方种族体型等）原样返回，保证不报错。
        /// </summary>
        public static string BodyTypeDisplayName(string defName)
        {
            switch (defName)
            {
                case "Thin": return "纤细";
                case "Fat": return "肥胖";
                case "Hulk": return "壮硕";
                case "Female": return "女性";
                case "Male": return "男性";
                default: return defName;
            }
        }

        /// <summary>
        /// Transpiler: replace matched ldstr English directly with ldstr Chinese.
        /// </summary>
        public static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
        {
            foreach (var code in instructions)
            {
                if (code.opcode == OpCodes.Ldstr
                    && code.operand is string str
                    && KeyForString.TryGetValue(str, out var localized))
                {
                    // Keep original labels to avoid "Label not marked" branch-target errors.
                    var newLoad = new CodeInstruction(OpCodes.Ldstr, localized);
                    newLoad.labels.AddRange(code.labels);
                    yield return newLoad;
                }
                else
                {
                    yield return code;
                }
            }
        }
    }
}
